server:
  port: 8080
spring:
  application:
    name: fitcliff-gym
  datasource:
    url: jdbc:postgresql://${host}:5432/postgres
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        "[default_schema]": public
#  data:
#    mongodb:
#      uri: mongodb+srv://${mongouser}:${mongopassword}@${mongohost}/?retryWrites=true&w=majority&appName=Cluster0
#      database: fitcliff-mongo
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 256MB
      max-file-size: 256MB
logging:
  level:
    root: INFO
    com.gym.fitcliff: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: C:/logs/fitcliff-app.log  # Specify the file name and path
 
