server:
  port: 8080
spring:
  application:
    name: fitcliff-gym
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Welcome4
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        "[default_schema]": public
#  data:
#    mongodb:
#      uri: mongodb+srv://${MongoDbUser}:${MongoDbPassword}@cluster0.sq7ss.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#      database: fitcliff-mongo
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 256MB
      max-file-size: 256MB
logging:
  level:
    root: DEBUG
    org.apache.tomcat.util.net.NioEndpoint: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: D:/logs/myapp.log  # Specify the file name and path
 
