server:
  port: 8081
  servlet:
    context-path: /v1

spring:
  application:
    name: fitcliff-gym
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: ${PostgreSQLUsername}
#    password: ${PostgreSQLPassword}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        "[default_schema]": public
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
      globally_quoted_identifiers: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    mongodb:
      uri: mongodb+srv://${MongoDbUser}:${MongoDbPassword}@cluster0.sq7ss.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: fitcliff-mongo
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 256MB
      max-file-size: 256MB