server:
  port: 8081
  servlet:
    context-path: /v1

spring:
  application:
    name: lrb-user
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgresuser
    password: admin@1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        "[default_schema]": public