openapi: 3.0.2
info:
  title: Gym management system.
  version: 1.0.0
  description: Internal API of the Gym mangement system.
servers:
  - url: 'https://com.fitcliff/api/{version}'
    description: Productive environment
    variables:
      version:
        default: v1
  - url: 'https://fitcliff/api/{version}'
    description: Acceptence environment
    variables:
      version:
        default: v1
tags:
  - name: customer
    description: Customer Management.
  - name: group
    description: Group of customer
  - name: image
    description: image.
  - name: documentId
    description: documentId.
paths:
  '/admin/documentId':
    post:
      description: Create document entry
      tags: [ documentId ]
      operationId: createDocumentId
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                image:
                  type: string
                  format: binary
      security:
        - oidc: [ ]
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentImage'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
  '/admin/documentId/{id}':
    get:
      description: Download document Id
      tags:
        - documentId
      operationId: getDocumentId
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      security:
        - oidc: [ ]
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
    delete:
      description: Delete document Id
      tags:
        - image
      operationId: deleteDocumentId
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      security:
        - oidc: [ ]
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
  '/admin/image':
    post:
      description: Create Image entry
      tags: [ image ]
      operationId: createImage
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                image:
                  type: string
                  format: binary
      security:
        - oidc: [ ]
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
  '/admin/image/{id}':
    get:
      description: Download image
      tags:
        - image
      operationId: getImage
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      security:
        - oidc: [ ]
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
    delete:
      description: Delete image
      tags:
        - image
      operationId: deleteImage
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      security:
        - oidc: [ ]
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
  '/admin/group':
    get:
      description: Get Group list
      tags:
        - group
      operationId: getGroups
      security:
        - oidc: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
    post:
      description: Create new group
      tags: [ group ]
      operationId: createGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      security:
        - oidc: [ ]
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
  '/admin/customer/search/{text}':
    get:
      description: Search Customers
      tags: [ customer ]
      operationId: searchCustomerBy
      parameters:
        - in: path
          name: text
          required: true
          schema:
            type: string
      security:
        - oidc: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
  '/admin/customer/search':
    post:
      description: Search Customers
      tags: [ customer ]
      operationId: searchCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchCustomer'
        required: true
      security:
        - oidc: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
  '/admin/customer/{id}':
    get:
      description: Get customer details for an id
      tags:
        - customer
      operationId: getCustomer
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      security:
        - oidc: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
  '/admin/customer':
    get:
      description: Get Customer list
      tags:
        - customer
      operationId: getCustomers
      security:
        - oidc: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
    post:
      description: Create new Customer
      tags: [ customer ]
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      security:
        - oidc: [ ]
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
    put:
      description: Update Customer
      tags: [ customer ]
      operationId: updateCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      security:
        - oidc: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    DocumentImage:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fileName:
          type: string
        cutomerId:
          type: integer
          format: int64
        createdOn:
          type: string
          format: date
        mongoId:
          type: string
          example: mongodb id
      required:
        - fileName
        - createdBy
        - createdOn
        - mongoId
    Image:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fileName:
          type: string
        cutomerId:
          type: integer
          format: int64
        createdOn:
          type: string
          format: date
        mongoId:
          type: string
          example: mongodb id
      required:
        - fileName
        - createdBy
        - createdOn
        - mongoId
    SearchCustomer:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
          minLength: 0
          exclusiveMinimum: true
          maxLength: 255
        email:
          type: string
          format: email
          minLength: 0
          exclusiveMinimum: true
          maxLength: 255
          example: a.b@gmail.com
        gender:
         type: string
         enum:
          - MALE
          - FEMALE
        regDate:
          type: string
          format: date
        joinDate:
          type: string
          format: date
        birthdate:
          type: string
          format: date
        address:
          type: string
        membershipAmount:
          type: string
        membershipDuration:
          type: string
          enum:
           - ONE_MONTH
           - THREE_MONTHS
           - SIX_MONTHS
           - ONE_YEAR
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
          minLength: 0
          exclusiveMinimum: true
          maxLength: 255
        email:
          type: string
          format: email
          minLength: 0
          exclusiveMinimum: true
          maxLength: 255
          example: a.b@gmail.com
        phones:
          type: array
          items:
            type: string
        gender:
         type: string
         enum:
          - MALE
          - FEMALE
        isActive:
          type: boolean
        regDate:
          type: string
          format: date
        joinDate:
          type: string
          format: date
        birthdate:
          type: string
          format: date
        address:
          type: string
        membershipAmount:
          type: string
        membershipDuration:
          type: string
          enum:
           - ONE_MONTH
           - THREE_MONTHS
           - SIX_MONTHS
           - ONE_YEAR
        payments:
          type: array
          items:
            $ref: '#/components/schemas/IndividualPayment'
        group:
          $ref: '#/components/schemas/Group'
        image:
          type: integer
          format: int64
        documentImage:
          type: integer
          format: int64
        membershipType:
          type: string
          enum:
            - INDIVIDUAL
            - GROUP
      required:
        - firstName
        - gender
        - phones
        - joinDate
        - birthdate
        - address
        - membershipAmount
        - membershipDuration
    IndividualPayment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        cutomerId:
          type: integer
          format: int64
        date:
          type: string
          format: date
        amount:
          type: string
        pendingAmount:
          type: string
        paymentType:
          type: string
          enum:
           - CASH
           - UPI
      required:
        - cutomerId
        - amount
        - paymentType
    GroupPayment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        groupId:
          type: integer
          format: int64
        date:
          type: string
          format: date
        amount:
          type: string
        pendingAmount:
          type: string
        paymentType:
          type: string
          enum:
           - CASH
           - UPI
      required:
        - groupId
        - amount
        - paymentType
    Group:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        date:
          type: string
          format: date
        payments:
          type: array
          items:
            $ref: '#/components/schemas/GroupPayment'
    ValidationError:
      description: A response object that reflects the validation errors occured while validating the input
      type: object
      required:
        - message
        - details
      properties:
        message:
          description: Overall message
          type: string
        details:
          description: Array with detailed error messages
          minItems: 1
          items:
            type: object
            required:
              - location
              - param
              - value
              - msg
            properties:
              location:
                description: 'Location, where the error occured'
                type: string
                enum:
                  - body
                  - path
                  - param
              param:
                description: 'Field path with information, where the error occured'
                type: string
                example: 'fieldName1[3].fieldName2'
              value:
                description: 'Caller provided value that caused the validation error, empty string if nothing was provided'
                type: string
              msg:
                description: 'Validation message for the field, giving the exact reason'
                type: string
  responses:
    Created:
      description: Stored new data for that reference period (i. e. nothing existed before)
    Unauthorized:
      description: Unauthorized (invalid credentials or deactivated customer)
    ValidationError:
      description: Validation errors occured
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    InvalidMediaType:
      description: Invalid media type
    NotFound:
      description: Data not existing for given period
    ServerError:
      description: Server Error
  securitySchemes:
    oidc:
      type: openIdConnect
      description: Api key provided to the member states by the filtcliff managment
      openIdConnectUrl: 'https://gym.fitcliff/auth'
security:
  - oidc: [ ]